### ISSUE TITLE
404 not found -  ch1_getting_started

### ISSUE THREAD

**Issue by jinfanv** [madhusudhankonda/elasticsearch-in-action#1]
Hi, I'm following the instruction in chapter 2 - elasticsearch-in-action-second-edition but the script **ch1_getting_started.txt** It's not available in the repository. Could you update it?

**Comment by SquirrelCoder** [comment]
It's called `ch2_getting_started.txt`.

https://github.com/madhusudhankonda/elasticsearch-in-action/blob/main/kibana_scripts/ch2_getting_started.txt
